### ISSUE TITLE
ESP8266 Support

### ISSUE THREAD

**Issue by darnold64** [tkem/CarreraDigitalControlUnit#14]
Firstly, thanks for a great tool for slot car tinkerers.  The library works great on an Arduino Uno.  I tried it on a ESP8266 NodeMCU and unfortunately the board starts rebooting and I get this in the serial monitor: 

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 3424, room 16 
tail 0
chksum 0x2e
load 0x3fff20b8, len 40, room 8 
tail 0
chksum 0x2b
csum 0x2b
v00047aa0
~ld

I am assuming it has something to do with the ESP8266 and its ability to handle the CU read.  I was wondering if you had any suggestions.  Thanks in advance.

**Comment by tkem** [comment]
@darnold64: Thanks for your interest!
I tested the library with Arduino Uno/Nano and Raspberry Pi Pico, but not with ESP8266.
I have a NodeMCU board lying around somewhere, so I might give it a try, but it will take a while.
In the mean time, if you find a way to make this work on ESP8266, your input will surely be welcome!

**Comment by darnold64** [comment]
Thomas, 
Thank you for the quick response.  As mentioned, the library works great with the Arduino Uno.  However, I am in the process of building some driver dashboards with TFT displays and was looking to use the ESP8266 or ESP32 to drive everything since I have a reasonable amount of experience with these boards. I managed to get the code to run without constantly resetting the board by doing the following: if (CarreraCommandPacket packet = cu.read(0)) I believe the ESP8266 doesn’t like blocking and so resets itself through the watchdog function waiting for the read to happen.  This is my theory anyway.  I may need to play around with the value for cu.read(). I haven’t had a chance to test it on the track yet (my laptop died on me yesterday).  Once I get the laptop working again I will let you know what happens.

**Comment by tkem** [comment]
I just re-checked, and both the CommandSniffer and DataLogger examples seem to work fine with my ESP8266 (NodeMCU V3) boards in the Arduino IDE with the "NodeMCU 1.0 (ESP-12E Module)" board selected.
Thinking about it, I guess I _did_ do some tests with that board, at least some `#ifdef`s for ESP8266 do exist in the code - sorry, it's been a while...
However, if you don't connect your board to a Control Unit, it is reasonable the watchdog will reset the board when doing a blocking `read()` without timeout, since there won't be any data to return, so `read()` will wait forever. I was also able to reproduce this by switching off the Control Unit. So I guess as soon as you're able to connect again, things will turn out fine.

**Comment by darnold64** [comment]
Thanks again.  I managed to revive my laptop and was able to test things on the track.  read(0) does the trick.  It works fine whether connected to the track or not--no resetting of the ESP and I am able to capture the CU messages.

**Comment by tkem** [comment]
@darnold: I added cu.read() timeouts to the examples, so there should be no more surprises on ESP8266 platforms. The "startlight" example should also show blinking LEDs if no connection to the CU can be established.
Thanks for your efforts!
